[08/27] react에서 typescript를 잘 사용하는 방법
JNU-econovation/hotsix-study pull request #16
Opened 2023-08-27 01:58 UTC by loopy-lim

2023-08-27 14:26 UTC, 2yunseong requested changes
👍

2023-08-27 14:26 UTC, 2yunseong commented on cheasueng/ReactTypescript.md
> +};
평소에 propsWithChildren만 썼는데 이걸로 강제해줄 수 있겠네요 👍

2023-08-27 14:26 UTC, 2yunseong commented on cheasueng/ReactTypescript.md
> +};
FC 관련 릴리즈노트 찾아주세요~ 
추가로 스터디에서 다뤘던 관련 글 함께 공유합니다.
https://yceffort.kr/2022/03/dont-use-react-fc

2023-08-30 13:33 UTC, loopy-lim commented on cheasueng/ReactTypescript.md
> +  };
initial한 값일때는 generic으로 선언 되어 있을 지라도 추론을 못하는 것으로 알고 있습니다!!

2023-08-30 13:40 UTC, loopy-lim commented on cheasueng/ReactTypescript.md
> +};
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46643
에서 말이 보여진봐 @types/react [16.9.48 to npm](https://www.npmjs.com/package/@types/react)에서 이루어졋네요.

독특하게 react가 아니라 여기에서 관리하고 있습니다

2023-08-30 23:13 UTC, 2yunseong commented on cheasueng/ReactTypescript.md
> +};
생각해보니 react는 flow를 사용하고 있어서 따로 TS에 대한 타입은 지원하지 않겠네요!!
DefinitelyTyped 관련해서는 러닝타입스크립트 마지막 내용에 @types 와 함께 나오는 걸로 알고 있습니다(저도 생각을 못했네욤)

2023-08-30 23:13 UTC, 2yunseong approved these changes

2023-09-02 20:00 UTC, DWAN-00 approved these changes

2023-09-03 03:58 UTC, bada308 approved these changes

2023-09-03 07:14 UTC, merged