[08/27] tsconfig 초기설정
JNU-econovation/hotsix-study pull request #17
Opened 2023-08-27 06:38 UTC by DWAN-00

초반에 꽉 잡고가야할 부분인 것 같아 가져와봤습니다. 내용은 블로그 참고했습니다.

2023-08-27 14:37 UTC, 2yunseong requested changes
config부터 파시다니 처음부터 단단히 가져가시려는 동완님의 모습이 인상깊네요!!

2023-08-27 14:37 UTC, 2yunseong commented on dongwan/tsconfig_setting.md
> +    "ts-node": {"esm": true},
이건 무엇인가요?

2023-08-27 14:37 UTC, 2yunseong commented on dongwan/tsconfig_setting.md
> +        "src/types.d.ts"
include 속성에 src를 넣어줬음에도 불구하고 files를 써야하는 이유가 있나요?

2023-08-27 14:37 UTC, 2yunseong commented on dongwan/tsconfig_setting.md
> +        dom: setTimeout, console.log 등 dom에서 지원해주는 기능들을 사용하기 위함
setTimeout 과 console.log는 dom 에 속하지 않는다고 생각하는데 어떠세요 🧐
https://www.typescriptlang.org/tsconfig#lib

2023-08-27 14:37 UTC, 2yunseong commented on dongwan/tsconfig_setting.md
> +    include 속성은 files 속성과 같이 프로젝트에서 컴파일할 파일들을 지정하는 속성이지만, **와일드 카드** 패턴으로 지정한다는 점에서 차이가 있다. 또한 include는 files 속성과는 달리 exclude보다 약해 include에 명시되어 있어도 exclude에도 명시되어 있으면 제외 되게 된다.
오 새롭게 안 사실!! 👍

2023-08-28 08:54 UTC, bada308 approved these changes

2023-08-28 08:54 UTC, bada308 commented on dongwan/tsconfig_setting.md
> +    ```
wild card 사용법에 대해 자세히 알게되어 좋았습니다

2023-08-30 13:57 UTC, loopy-lim approved these changes
역시 Base부터 챙기시는 동완님!!
저도 새롭게 알고 가는 사실이 많은거 같아요!!
다음 스터디가 기대됩니다!!

2023-08-30 13:57 UTC, loopy-lim commented on dongwan/tsconfig_setting.md
> +        // 'es3', 'es5', 'es2015', 'es2016', 'es2017','es2018', 'esnext' 가능
어디선가 많이 본거 같지 않나요??
어디일까요?
힌트. 
1. 저희가 js로 react쓰면서도 많이 써요!
2. 눈이 내린다 눈이 내려!

2023-08-30 13:57 UTC, loopy-lim commented on dongwan/tsconfig_setting.md
> +    - react-native : .js 파일로 컴파일 된다. (JSX 코드가 그대로 유지됨)
오 \_jsx()이 모양이 여기서 나오는 거였군요!!

2023-08-30 18:21 UTC, DWAN-00 commented on dongwan/tsconfig_setting.md
> +        dom: setTimeout, console.log 등 dom에서 지원해주는 기능들을 사용하기 위함
음 그런 것 같네요.. 그러면 그 둘은 브라우저 딴에서 제공하는 그냥 실행어일까요?

2023-08-30 18:23 UTC, DWAN-00 commented on dongwan/tsconfig_setting.md
> +        // 'es3', 'es5', 'es2015', 'es2016', 'es2017','es2018', 'esnext' 가능
babel..일까요?

2023-08-31 01:00 UTC, 2yunseong commented on dongwan/tsconfig_setting.md
> +        dom: setTimeout, console.log 등 dom에서 지원해주는 기능들을 사용하기 위함
사실은 `dom.d.ts`에 속합니다 ㅎㅎ 본의아니게 속여서 죄송해요 
setTimeout과 console 은 브라우저에서 제공하는 window 객체에 속해있기 때문에, dom.d.ts 파일에 접근하면 해당 타입을 확인할 수 있을거에요.
<img width="732" alt="image" src="https://github.com/JNU-econovation/hotsix-study/assets/56749516/901a5373-c211-4aa6-86a9-f4f27d4a2681">
다만 브라우저 환경에서 지원할 때는 setTimeout과 console은 window 객체에 속해있고, 노드 환경에서는 독립적으로 존재합니다.
실제로 확인해보셔도 좋을 것 같아요. 또 브라우저 환경과 노드환경에서 setTimeout을 사용할 때 반환하는 값이 다르니, 그 점도 한번 살펴보시면 좋을 것 같습니다.

2023-08-31 05:24 UTC, loopy-lim commented on dongwan/tsconfig_setting.md
> +        // 'es3', 'es5', 'es2015', 'es2016', 'es2017','es2018', 'esnext' 가능
@DWAN-00 
오! 그중 하나에요!! 정답입니다!! snowpack이나, babel이나, rollup등이 있죠!!
사실 제가 질문을 조금 이상하게 말하긴 했는데 TS는 사실 컴파일러라는 사실을 알려드리고 싶었어요!!

2023-09-02 12:33 UTC, 2yunseong approved these changes

2023-09-02 12:53 UTC, DWAN-00 commented on dongwan/tsconfig_setting.md
> +    "ts-node": {"esm": true},
컴파일 디폴트를 Common JS가
아닌 ecma script로 잡는 것 같습니다

2023-09-03 02:54 UTC, merged