[08/27] typescript를 사용하는 이유
JNU-econovation/hotsix-study pull request #18
Opened 2023-08-27 08:33 UTC by dle234

2023-08-27 14:43 UTC, 2yunseong requested changes
고생하셨습니다 ~ 완강을 기원합니다 :)

2023-08-27 14:43 UTC, 2yunseong commented on kayeon/타입스크립트 _사용하는_이유.md
> +   -> 너무 많은 변화와 하위호환성 유지의 어려움을 지적받게 되며 javascript의 체계를 유지하면서 조금씩 고쳐나가자
정적타이핑, 인터페이스, 제네릭은 자바스크립트 어디에 적용되었을까요? 예시를 들어주시면 좋을 것 같아요!

2023-08-27 14:43 UTC, 2yunseong commented on kayeon/타입스크립트 _사용하는_이유.md
> +- 에러가 많이 보여서 불편함.
ㅋㅋㅋㅋㅋ참을수없죠

2023-08-27 14:43 UTC, 2yunseong commented on kayeon/타입스크립트 _사용하는_이유.md
> +* 처음부터 세팅에 대해 이해하려고 하지 말고 가급적 세팅이 되어 있는 프로젝트로 시작하기(예) vite, tsup...) -->
다만 어느정도 익숙해졌다면 알고 써야할 것 같아요!

2023-08-27 14:43 UTC, 2yunseong commented on kayeon/타입스크립트 _사용하는_이유.md
> +- Literal Types: 문자열 또는 숫자 값 자체를 타입으로 지정.
어떤걸 예시로 들어볼 수 있을까요?

2023-08-28 08:52 UTC, DWAN-00 approved these changes

2023-08-28 08:52 UTC, DWAN-00 commented on kayeon/타입스크립트 _사용하는_이유.md
> +```
튜플과 배열의 다른점도 설명해 주시면 좋을 것 같아요

2023-08-28 08:53 UTC, bada308 approved these changes

2023-08-28 08:53 UTC, bada308 commented on kayeon/타입스크립트 _사용하는_이유.md
> +* Tuple (튜플): TypeScript에서 지원하는 고정된 개수의 요소로 이루어진 배열 타입으로, 각 요소는 서로 다른 타입일 수 있습니다.
python에서의 tuple과 typescript tuple은 비슷하지만 다르네요!

2023-09-02 12:45 UTC, dle234 commented on kayeon/타입스크립트 _사용하는_이유.md
> +- Literal Types: 문자열 또는 숫자 값 자체를 타입으로 지정.
let x: "사람" = "사람"; 처럼 사람 이라는 문자열 자체가 타입이 되는것을 예시로 들 수 있을것같아요!! 
x = 사람 이외이 문자열 대입 불가

2023-09-02 12:49 UTC, dle234 commented on kayeon/타입스크립트 _사용하는_이유.md
> +```
넵!!
튜플은 정확히 명시된 개수 만큼의 원소만을 가질 수 있다는 점에서 차이가 있습니다!
예)) 
const AA: [string, number] = ['문자열', 1, 2]; -> 개수 초과돼서 에러

2023-09-02 12:58 UTC, dle234 commented on kayeon/타입스크립트 _사용하는_이유.md
> +   -> 너무 많은 변화와 하위호환성 유지의 어려움을 지적받게 되며 javascript의 체계를 유지하면서 조금씩 고쳐나가자
정적 타이핑은 자바스크립트의 개념이 들어가 타입을 사용할 수 있게 됐고,(const a: string = "A")
나머지도 마찬가지로 자바스크립트의 변수 혹은 함수 등의 타입을 지정해주는 부분에 적용 된 것 같습니다..!(질문의 의도가 이게 맞을까요...?🥲)

2023-09-02 14:09 UTC, loopy-lim approved these changes
잘 읽었어요!!
타입스크립트의 근본부터 접근하시는 군요!!
탄탄하게 공부하면 좋을것 같습니다!!

2023-09-02 14:09 UTC, loopy-lim commented on kayeon/타입스크립트 _사용하는_이유.md
> +- Typescript : Javascript(prototype 객체기반 함수형 스크립트)+ 기타 문법
이를 superset 언어라고 표현한답니다!

2023-09-02 14:09 UTC, loopy-lim commented on kayeon/타입스크립트 _사용하는_이유.md
> +}
좀 더 찾아보면... 사실 안써요 ㅋㅋㅋㅋㅋㅋ
나중에 왜 안쓰는지 추가하면 좋을꺼 같아요

2023-09-03 01:04 UTC, dle234 commented
> 고생하셨습니다 ~ 완강을 기원합니다 :)

2023-09-03 02:53 UTC, 2yunseong commented on kayeon/타입스크립트 _사용하는_이유.md
> +   -> 너무 많은 변화와 하위호환성 유지의 어려움을 지적받게 되며 javascript의 체계를 유지하면서 조금씩 고쳐나가자
네!! 사실 질문이 조금 이상하긴 했어요ㅠㅠ 그래도 답변해주셔서 감사합니다.

2023-09-03 02:53 UTC, 2yunseong approved these changes

2023-09-03 02:55 UTC, merged