[08/27] 집합의 관점에서 type 바라보기
JNU-econovation/hotsix-study pull request #19
Opened 2023-08-27 12:44 UTC by bada308

2023-08-27 12:48 UTC, DWAN-00 commented on bada/집합의_관점에서_타입_바라보기.md
> + home: '제호베레이 행성'
가모라씨가 제호베레이 행성 출신이군요

2023-08-27 12:49 UTC, DWAN-00 approved these changes

2023-08-27 14:51 UTC, 2yunseong requested changes
고생하셨습니다~ 저도 처음에 많이 어려워했던 부분 top 3에 드는 내용이였는데 다시 한 번 복습할 수 있어 좋았습니다!

2023-08-27 14:51 UTC, 2yunseong commented on bada/집합의_관점에서_타입_바라보기.md
> + home: '제호베레이 행성'
매개변수로 `enterEarth`에 전달할 때는 문제 없지만, 다음과 같이 작성하면 오류가 발생하는데요,
왜 그럴까요?
```ts
const Gamora:Person = {
 name: '가모라',
 birth: new Date('1900/11/24'),
 death: new Date('2018/05/31'),
 home: '제호베레이 행성'
}
```

2023-08-27 14:51 UTC, 2yunseong commented on bada/집합의_관점에서_타입_바라보기.md
> +}
결국 `introduce`에 전달되는 `someone`은 사용시기에 `Person` 아니면 `Developer` 둘 중 하나가 오게됩니다.
`introduce`는 어떻게 사용시기에 타입을 알 수 있을까요?

2023-08-27 14:51 UTC, 2yunseong commented on bada/집합의_관점에서_타입_바라보기.md
> +-> 유니온 타입과 인터섹션 타입이 기존에 알고 있던 집합의 관점과는 약간 다르기 때문에 헷갈리지 않게 주의하자!
저도 처음에는 많이 헷갈렸습니다ㅠㅠ

2023-08-30 13:24 UTC, bada308 commented on bada/집합의_관점에서_타입_바라보기.md
> + home: '제호베레이 행성'
**객체 리터럴**을 변수에 할당하거나 인수로 전달할 때 초과 프로퍼티 검사를 받기 때문입니다!
- 초과 프로퍼티 : 타입에 정의된 프로퍼티 외의 다른 초과된 프로퍼티를 갖는 객체를 변수에 할당할 수 없도록 막는 기능

초과 프로퍼티 검사를 피하기 위한 방법으로 타입 단언 `as` 방법을 사용할 수 있습니다.

2023-08-30 13:24 UTC, bada308 commented on bada/집합의_관점에서_타입_바라보기.md
> + home: '제호베레이 행성'
타입 단언도 강의 듣고 공부해보겠습니다~!

2023-09-02 12:34 UTC, 2yunseong approved these changes

2023-09-02 14:11 UTC, loopy-lim approved these changes
Type을 잘 쓰는 첫번째를 쓰셨군요!!
저도 인터렉션 타입이나 유니온 타입등을  잘 쓰고 싶은데 항상 너무 어렵더라구요 ㅠㅠ

2023-09-02 14:11 UTC, loopy-lim commented on bada/집합의_관점에서_타입_바라보기.md
> +구조적 타이핑이란 객체가 어떤 타입에 부합하는 **최소한의 특징**을 가지고 있다면, 그냥 그 타입에 해당하는 것이라고 간주하는 것.
javascript의 duck type과 무슨 차이가 있을까요?

2023-09-02 14:11 UTC, loopy-lim commented on bada/집합의_관점에서_타입_바라보기.md
> +-> 유니온 타입과 인터섹션 타입이 기존에 알고 있던 집합의 관점과는 약간 다르기 때문에 헷갈리지 않게 주의하자!
저도... 많이 헷갈렸어요...(사실 지금도 헷갈림 ㅠㅠ)

2023-09-03 02:28 UTC, merged