dwan 2week
JNU-econovation/hotsix-study pull request #20
Opened 2023-09-02 19:56 UTC by DWAN-00

[09/03] generic과 활용
generic을 왜 사용하는지, component에 어떻게 활용할 수 있을지 생각해봤습니다. 피드백 환영이에요~

2023-09-03 06:48 UTC, bada308 approved these changes

2023-09-03 06:48 UTC, bada308 commented on dongwan/TS_generic.md
> +  V : value
오 변수명에 이런 뜻이 있었군요

2023-09-03 06:48 UTC, bada308 commented on dongwan/TS_generic.md
> +  export function TabBar<T extends { id: number; name: string }>(
컴포넌트에도 제네릭을 사용할 수 있군요!!

화살표 함수에서는 제네릭을 어느 위치에 선언하는지 궁금해서 찾아봤습니다.

```ts
// 화살표 함수
const func = <T> () => {}

// 함수 선언식
function func<T>(){}
```

2023-09-04 04:52 UTC, dle234 commented on dongwan/TS_generic.md
> +데이터라는 객체의 프로퍼티는 <p>고 해당 프로퍼티의 타입이 string이 아니라면 아무것도 리턴하지 않는다.
리액트에서 타입스크립트를 어떻게 활용하는지 몰랐는데 잘 읽었어요! 혹시 데이터라는 객체의 프로퍼티가 <p> 태그라는 게 잘 이해가 안되는데 조금 더 자세히 설명해주실 수 있을까요!

2023-09-05 07:04 UTC, DWAN-00 commented on dongwan/TS_generic.md
> +데이터라는 객체의 프로퍼티는 <p>고 해당 프로퍼티의 타입이 string이 아니라면 아무것도 리턴하지 않는다.
음
`interface data : Data {
  p : string 
}`
이런 느낌인거죠...! 설명이 됐을까요

2023-09-05 11:55 UTC, 2yunseong requested changes
고생하셨습니다! 어려운 주제라서 같이 고민할 거리를 몇개 남겨놓아봤씁니다~

2023-09-05 11:55 UTC, 2yunseong commented on dongwan/TS_generic.md
> +데이터라는 객체의 프로퍼티는 <p>고 해당 프로퍼티의 타입이 string이 아니라면 아무것도 리턴하지 않는다.
예시에서 data의 타입이 Data라는 코드가 없는 것 같아요!

2023-09-06 01:33 UTC, DWAN-00 commented on dongwan/TS_generic.md
> +  ```
불필요한 어노테이션이었네요

2023-09-06 02:39 UTC, DWAN-00 commented on dongwan/TS_generic.md
> +  최종적으로 컴포넌트의 타입을 이렇게 부여할 수 있다. 재사용하기에도 용이하고 타입 반환에도 용이하다.
음 재사용성이 아니라 가독성에 대한 이야기였던 것 같기도 하네요. 유니온이나 오버로딩을 사용했을 때 어노테이션이나 호출을 여러번해서 코드가 더러워지는 단점이 있다고 생각했는데, 제네릭으로 타입 변수화 하면 한번 할당하고 호출만 해주면 되는게 장점이라고 생각했습니다.

2023-09-06 02:44 UTC, DWAN-00 commented on dongwan/TS_generic.md
> +  - 유동적이고 범용적인게 TS에서 꼭 좋은 것인지는 모르겠다.
음 어렵긴 한데 이해했습니다. 다음에 객체지향 관련해서 발표해보면 좋을 것 같네요.

2023-09-07 15:37 UTC, loopy-lim commented on dongwan/TS_generic.md
> +- generalize type : 데이터의 타입을 일반화 한다.
제네릭은 많은 다른 언어에서 지원하는데 C++, Java랑 다른게 무엇일까요?

2023-09-07 15:44 UTC, loopy-lim commented on dongwan/TS_generic.md
> +  const value = data[property] as string;
여기에서 as 로 지정한 이유는 무엇인가요?

2023-09-08 12:12 UTC, DWAN-00 commented on dongwan/TS_generic.md
> +                : " bg-slate-200";
아 그렇네용 해외 포스팅보고 가져온 코드라서 생각못했네용~

2023-09-09 03:14 UTC, DWAN-00 commented on dongwan/TS_generic.md
> +  const value = data[property] as string;
예시를 가져온 거긴 한데 유동적으로 사용하려고 generic을 사용했는데 string으로 단언할 필요는 없었네요

2023-09-09 05:32 UTC, 2yunseong requested changes

2023-09-09 05:32 UTC, 2yunseong commented on dongwan/TS_generic.md
> +  최종적으로 컴포넌트의 타입을 이렇게 부여할 수 있다. 재사용하기에도 용이하고 타입 반환에도 용이하다.
@DWAN-00 
> 음 재사용성이 아니라 가독성에 대한 이야기였던 것 같기도 하네요.

같기도 한건가요? 그러면 예시에서 표현하는 내용은 가독성 위주로 읽으면 되는 건가요? `~것 같다` 라는  표현때문에 저는 동완님이 어떤 의도이신지 명확하게 파악하기 어렵습니다. 정답은 없으니까 동완님의 진짜 생각이 궁금합니다~ 저는 이 글을 읽고 검토해주는 사람이 아니라 스터디로 의견을 공유하는 사람이니까요!! 👍 

만약 가독성 측면에서 위 예시를 들었다면, 동완님이 생각하시는 위 예시에서 **가독성 측면에서** 어떤 부분이 가독성이 좋았는지 들려주실 수 있나요? 물론 답변으로 설명해주셨지만 답변으로는 특정 상황을 그리기 힘들었어요. 코드로 예시를 들어주면 좋겠습니다!!

2023-09-10 03:28 UTC, DWAN-00 commented on dongwan/TS_generic.md
> +  최종적으로 컴포넌트의 타입을 이렇게 부여할 수 있다. 재사용하기에도 용이하고 타입 반환에도 용이하다.
```typescript
function User(
  name: string,
  age: number,
  email: string,
  isActive: boolean,
  role: string[],
  address: { street: string; city: string }
): string {
  return `${name}, ${age}, ${email}, ${isActive}, ${role.join(', ')}, ${address.street}, ${address.city}`;
}
``` 
User에대해 위와 같이 일반적으로 선언한다면 코드가 너무길고 모든 프로퍼티에 대한 타입을 다 지정해주어야합니다. 제네릭을 사용하면
```typescript
function processUserData<T>(
  data: T
): string {
  return `${data.name}, ${data.age}, ${data.email}, ${data.isActive}, ${data.role.join(', ')}, ${data.address.street}, ${data.address.city}`;
}

``` 
짧게 나타낼 수 있습니다. 물론 첫번째 코드도 프로퍼티의 타입을 바로 확인할 수 있다는 장점도 있겠지만
저는 개인적으로 짧게 나타내는 편이 가독성과 길이 면에서 
좋다고 생각되네요...!

2023-09-10 03:42 UTC, dle234 approved these changes

2023-09-10 04:19 UTC, 2yunseong commented on dongwan/TS_generic.md
> +  최종적으로 컴포넌트의 타입을 이렇게 부여할 수 있다. 재사용하기에도 용이하고 타입 반환에도 용이하다.
@DWAN-00 
짧게만 나타내고 싶다면, 모든 프로퍼티를 객체로 묶는 것이 하나의 방법이라고 봅니다.
```ts
interface Address {
  street: string;
  city: string;
}

interface User {
  name: string,
  age: number,
  email: string,
  isActive: boolean,
  role: string[],
  address: Address
}

function User (data:User) {
 return `${data.name}, ${data.age}, ${data.email}, ${data.isActive}, ${data.role.join(', ')}, ${data.address.street}, ${data.address.city}`;
}
```
이 코드는 오류가 발생하는데 일단 가독성 측면에서 이렇게 작성했다고 생각해볼께요. 
```ts
function processUserData<T>(
  data: T
): string {
  return `${data.name}, ${data.age}, ${data.email}, ${data.isActive}, ${data.role.join(', ')}, ${data.address.street}, ${data.address.city}`; 
}
```
그러면 사용처에서 이렇게 사용할 텐데요!
```ts
processUserData({
 // 어떤 객체를 넣을까?
});
```
제 3자가 이 processUserData를 호출할 때, name, age, email, isActive, role, address 속성이 있는 객체를 매개변수로 넘겨주는 것을 보장할 수 있나요?

제네릭을 사용했다는 것은 T에는 어느 타입이든 올 수 있음을 의미하는데요, 지금 processUserData의 매개변수로 어느 타입이 와도 됨을 허용해주셨는데 이러면 제 3자는 의도와 다르게 사용할 수 있을 것 같다는 생각입니다.
그런 사용 예시를 하나 남겨 놓을게요.

```ts
 processUserData({ x: 11, y : 12 }) // TS는 허용하나 사용할 때 오류 발생
```
코드가 짧아야 꼭 가독성이 높은 코드인가? 도 생각해보면 좋을 것 같아요!!

2023-09-11 01:28 UTC, DWAN-00 commented on dongwan/TS_generic.md
> +  최종적으로 컴포넌트의 타입을 이렇게 부여할 수 있다. 재사용하기에도 용이하고 타입 반환에도 용이하다.
자세한 예시 감사합니다...! 실습 때 느꼈듯이 직접 해보면서 생각해보는 시간이 필요할 것 같습니다.
공부방식도 학습 내용들이 제 언어로 남도록 잘 바꿔봐야할 것 같습니다..ㅎ

2023-09-11 06:09 UTC, 2yunseong approved these changes

2023-09-11 06:09 UTC, merged