[09/03] 함수 타입의 호환성
JNU-econovation/hotsix-study pull request #21
Opened 2023-09-03 01:28 UTC by dle234

타입의 호환성 중 함수와 관련된 타입 호환성에 대해 알아보았습니다

2023-09-03 10:49 UTC, 2yunseong requested changes
고생하셨습니다!

2023-09-03 10:49 UTC, 2yunseong commented on kayeon/함수 타입의 호환성.md
> +
**타입 안전성** 측면에서 생각해보면 쉬울 것 같아요!
`value`라는 매개변수에 `10`이라는 인자만 올수 있도록 선언한 함수에 (c)
다른 숫자가 올 수 있는 함수를 대입한다고 하면 무엇인가 이상하지 않으세요?

반대로 어떠한 숫자든 매개변수로 받을 수 있는 함수 타입에 특정 숫자 10이라는 타입을 인자로 받는 함수가 대입되는 경우도 생각해보면 좋을 것 같아요

2023-09-03 10:49 UTC, 2yunseong commented on kayeon/함수 타입의 호환성.md
> +**명목적 타이핑은 상속관계 지향, 구조적타이핑은 집합으로 표현하는 개념 지향.**
가연님만의 생각으로 풀어서 설명해주실 수 있나요??

2023-09-03 12:21 UTC, dle234 commented on kayeon/함수 타입의 호환성.md
> +
헉 감사합니다!! 이해했어요!!

2023-09-03 14:56 UTC, DWAN-00 approved these changes

2023-09-03 14:56 UTC, DWAN-00 commented on kayeon/타입스크립트 _사용하는_이유.md
> +* 처음부터 세팅에 대해 이해하려고 하지 말고 가급적 세팅이 되어 있는 프로젝트로 시작하기(예) vite, tsup...) -->
vite react가 type이 어느정도 지정돼 있었군요..! CRA는 확실히 쓸 이유가 없는 것 같습니다.. 어떻게 생각하시나요

2023-09-04 05:47 UTC, dle234 commented on kayeon/함수 타입의 호환성.md
> +**명목적 타이핑은 상속관계 지향, 구조적타이핑은 집합으로 표현하는 개념 지향.**
예를들어 구조적 타이핑인 타입스크립트의 인터페이스 A, B 가 있었을떄  B 가 A를 상속했다고 직접 명시하지 않아도 구조만 같으면(같은 집합이면?) 호환성이 있다고 보고, 명목적 타이핑인 자바의 경우 컴파일 타임에서 타입 검사 시 인터페이스의 내부 구조를 따르는지 확인을 하는 것이 아닌, 인터페이스의 이름 자체를 가지고 검사를 수행하여 그 명칭, 부모인지자식인지인 상속관계가 중요하다. 라고 볼 수 있을 것 같습니다!!

2023-09-04 10:57 UTC, 2yunseong commented on kayeon/함수 타입의 호환성.md
> +**명목적 타이핑은 상속관계 지향, 구조적타이핑은 집합으로 표현하는 개념 지향.**
명쾌한 설명 감사합니다 👍 👍

2023-09-05 04:45 UTC, loopy-lim approved these changes
typescript의 본질에 접근을 하고 계시는군요!!
저는 업케스팅과 다운케스팅을 잘 활용하지 않았는데 지금 생각해보면 아직도 개념 적립이 잘 되지 않았나봐요

2023-09-05 04:45 UTC, loopy-lim commented on kayeon/타입스크립트 _사용하는_이유.md
> +* 처음부터 세팅에 대해 이해하려고 하지 말고 가급적 세팅이 되어 있는 프로젝트로 시작하기(예) vite, tsup...) -->
Vite적극적으로 사용하는거 좋습니다!! ㅋㅋㅋㅋㅋㅋ
Vite도 컴파일 툴하고 비슷한 언저리라서 react말고 다른 node프로젝트를 구축할때 좋아요(vitest나.. electron이나...)

2023-09-05 04:45 UTC, loopy-lim commented on kayeon/함수 타입의 호환성.md
> +//이렇게 해주면 name 에만 접근하기 때문에 상관이 없다.
hasOwnProperty를 이용해서 가드를 한번 더 해주는 경우도 있는거 같더라구요!!
typescript는 좋아하지만 완전히 신뢰 하는게 아니라고 들었습니다 ㅋㅋㅋ

2023-09-10 12:49 UTC, 2yunseong approved these changes

2023-09-11 06:10 UTC, merged