[09/03] 타입 조작하기
JNU-econovation/hotsix-study pull request #22
Opened 2023-09-03 02:30 UTC by bada308

Q. 이전 커밋까지 모두 잡히는데 이유가 무엇인지 궁금합니다...

2023-09-03 02:45 UTC, 2yunseong commented
> Q. 이전 커밋까지 모두 pr에 올라오는 이유가 궁금합니다...

A. 현재 원본 저장소(JNU-econovation/hotsix-study)의 main의 커밋내역와  바다님 저장소의 main 브랜치를 비교해보시면 될 거 같습니다.
추가로 바다님 로컬까지해서 세 저장소의 커밋이력이 어떻게 되어있는지 간단하게 그림을 그려보면 이해하기 좋을 것 같아요~

2023-09-03 09:54 UTC, DWAN-00 approved these changes

2023-09-03 09:54 UTC, DWAN-00 commented on bada/타입_조작하기.md
> +  [key in keyof User] ?: User[key]
이렇게도 선택적 프로퍼티 지정을 해줄 수 있네요~

2023-09-03 09:54 UTC, DWAN-00 commented on bada/타입_조작하기.md
> +템플릿 리터럴 타입을 사용하면 타입이 너무 복잡해지기에 VScode's TS server의 동작이 느려지기도 한다.
효율과 성능 사이에서 적절한 타협이 필요한 부분이네요. 진행중인 작은 프로젝트에서는 리터럴 타입을 활용해봐도 괜찮을 것 같습니다.

2023-09-03 11:05 UTC, 2yunseong requested changes
고생하셨습니다~~

2023-09-03 11:05 UTC, 2yunseong commented on bada/타입_조작하기.md
> +User 인터페이스의 모든 프로퍼티가 선택적 프로퍼티인 새로운 인터페이스를 만들기 위해선 어떻게 해야할까?
심화) 다음과 같은 경우에는 어떻게 할 수 있을까요?
- User의 특정 속성만 골라서 타입으로 만들고 싶다.
- User의 특정 속성을 제외한 속성만 있는 타입을 만들고 싶다.

2023-09-03 11:05 UTC, 2yunseong commented on bada/타입_조작하기.md
> +템플릿 리터럴 타입을 사용하면 타입이 너무 복잡해지기에 VScode's TS server의 동작이 느려지기도 한다.
👍

2023-09-03 14:59 UTC, bada308 commented on bada/타입_조작하기.md
> +User 인터페이스의 모든 프로퍼티가 선택적 프로퍼티인 새로운 인터페이스를 만들기 위해선 어떻게 해야할까?
type Exclude<T, U> = T extends U ? never : T;
type Extract<T, U> = T extends U ? T : never;

이렇게 제네릭을 이용한 타입으로 구현할 수 있습니다!

2023-09-04 05:56 UTC, dle234 commented on bada/타입_조작하기.md
> +function getPropertyKey(person: Person, key: keyof typeof person) {
typeof 와 keyof을 같이 사용하면 유용하게 쓸 수 있는것 같네요!

2023-09-04 10:55 UTC, 2yunseong commented on bada/타입_조작하기.md
> +User 인터페이스의 모든 프로퍼티가 선택적 프로퍼티인 새로운 인터페이스를 만들기 위해선 어떻게 해야할까?
멋지네요 👍 타입스크립트에서도 제공하는 유틸리티 타입이라는 것도 있으니 알아보면 좋을 것 같습니다!!

2023-09-04 10:56 UTC, 2yunseong approved these changes

2023-09-07 14:51 UTC, bada308 commented on bada/타입_조작하기.md
> +```
typescript **Mapping Modifiers** 라는 키워드로 검색하면 나옵니다!

참고자료 : https://www.typescriptlang.org/docs/handbook/2/mapped-types.html

2023-09-11 06:10 UTC, merged