[09/03] Type Gard
JNU-econovation/hotsix-study pull request #24
Opened 2023-09-03 11:58 UTC by loopy-lim

2023-09-05 04:18 UTC, dle234 commented on cheasueng/TypeGard.md
> +function getShcool(arg: any): arg is Student {
is 를 이용한 방법은 처음 봐요! 그런데 특정 함수에서 동작하게 할 수 있다는게 잘 이해가 안가는데 조금 더 자세히 설명해주실수 있을까요,,!

2023-09-05 07:01 UTC, DWAN-00 approved these changes

2023-09-05 07:01 UTC, DWAN-00 commented on cheasueng/TypeGard.md
> +타입스크립트에서는 이 외의 방법으로 is, satisfy, as등을 지원합니다.
type guard는 단순히 오류를 막기위해 사용하는 건가요?
아니면 실제 사용할 때 타입을 완벽하게 좁히는게 그만큼 어려워서 사용하는 걸까요?

2023-09-05 13:14 UTC, 2yunseong requested changes
개발하시느라 고생하셨습니돠~~ 👍

2023-09-05 13:14 UTC, 2yunseong commented on cheasueng/TypeGard.md
> +  return arg.school;
반환값을 is ~ 로 명시한 건 좋은데 school은 string값 아닌가요?
반환하는 곳에 유의미한 타입을 검사하는 코드를 작성해야할 것 같아요!!

2023-09-07 16:06 UTC, loopy-lim commented on cheasueng/TypeGard.md
> +타입스크립트에서는 이 외의 방법으로 is, satisfy, as등을 지원합니다.
후자에 가깝습니다!!
ts는 결국 js위에서 돌아가므로 타입에 관해서 취약해질 수 밖에 없습니다. 그렇기 때문에 완벽하게 좁히는게 어려워 사용을 많이 합니다.(다시 말하면 구조적 타이핑 + prototype의 합한 결과랄까요?)

2023-09-07 16:15 UTC, loopy-lim commented on cheasueng/TypeGard.md
> +  return arg.school;
아 제가 예시를 잘못했군요 ㅠㅠ
```suggestion
function getShcool(arg: any): arg is Student {
    return typeof arg.school === string;
```
과 같이 했어야 했네요 타이핑을 수정할게요

2023-09-10 02:37 UTC, bada308 approved these changes

2023-09-10 02:41 UTC, bada308 approved these changes

2023-09-10 02:41 UTC, bada308 commented on cheasueng/TypeGard.md
> +}
`function getSchool(arg: Student) {}`로 표현하지 않고 `is`를 사용하는 특별한 이유가 있는지 궁금합니다!

2023-09-10 03:43 UTC, dle234 approved these changes

2023-09-10 09:20 UTC, loopy-lim commented on cheasueng/TypeGard.md
> +}
사실 코드 자체를 잘못 짰었는데 이것은 다음 아티클에 쓸께요!!
간단하게 말하자면 isStudent로 하네요...

2023-09-10 12:50 UTC, 2yunseong approved these changes

2023-09-11 06:11 UTC, merged