[09/10] 공식 명칭에는 상표 붙이기
JNU-econovation/hotsix-study pull request #25
Opened 2023-09-09 17:29 UTC by 2yunseong

제가 이번 주에 공부한 내용에는 채승님이 주제로 잡은 Type Guard 내용이 나옵니다~

어려운 부분이 있다면 어떤 부분이 어려운 지 코멘트로 남겨주세요. 감사합니다.

2023-09-13 05:49 UTC, loopy-lim approved these changes
무엇인가 새로운 것을 깨닫고 가는 순간인거 같습니다.

배울 수록 javascript를 넘는 무언가가 완성이 되는거 같네요. 그래서 사람들이 typescript를 배척하는건가...?

2023-09-13 05:49 UTC, loopy-lim commented on yunseong/attach_brand.md
> +}
오 이런 사용법으로 sorting이 되어 있다고 Interface를 강제할 수 있군요!!
symbol을 어떻게 하면 잘 해야할까? 라는 고민만 주구창창 있었는데 그것보다 이 방법이 훨신 직관적이고 좋은 것 같습니다!!

2023-09-13 05:49 UTC, loopy-lim commented on yunseong/attach_brand.md
> +따라서 AbsolutePath는 온전히 타입 시스템의 영역이 됩니다.
멋있는 말인거 같아요

자바스크립트와 다른 타입스크립트의 다른 매력?

2023-09-16 04:39 UTC, dle234 approved these changes

2023-09-16 16:43 UTC, bada308 commented
제가 상표 속성에 대해 이해한 내용을 간단히 적어봤는데, 처음 접하는 개념이라 제대로 이해했는지 모르겠습니다.
잘못 이해한 부분이나 부족한 부분이 있다면 알려주시면 감사하겠습니다!!!😄

> 구조적 타이핑의 특성 때문에 코드가 의도치 않은 결과를 도출할 때가 있는데, 이를 방지하고자 상표 속성이라는 것을 사용한다.
> 
> `_brand` 속성이 있는 값만 타입 검사를 통과하는데, `is` keyword 등을 사용해서 `_brand` 속성이 없는 값이라도 특정 조건을 만족한다면 타입 검사를 통과하도록 시스템을 속인다!
> 
> 이런 과정을 통해 타입 가드를 할 수 있다.

2023-09-16 16:44 UTC, bada308 approved these changes

2023-09-16 16:57 UTC, DWAN-00 requested changes

2023-09-16 16:57 UTC, DWAN-00 commented on yunseong/attach_brand.md
> +예시로 절대경로를 체크하는 코드를 살펴보겠습니다. 런타임에는 절대경로로 시작하는지 체크하기 쉽지만, 타입 시스템에서는 절대 경로를 판단하기 어렵기 때문에 상표 기법을 사용합니다.
타입 시스템에서 절대 경로를 판단하기 어려운 이유가 있을까요?

2023-09-16 16:57 UTC, DWAN-00 commented on yunseong/attach_brand.md
> +}
isSorted 함수에선 for문이 상표가 되는걸까요?

2023-09-16 17:11 UTC, 2yunseong commented on yunseong/attach_brand.md
> +타입스크립트가 평가하기에는 코드적으로 문제가 없습니다. 하지만 수학적(도메인)으로 따지면 3차원 벡터보다는 2차원 벡터를 사용해야 맞습니다.
@DWAN-00
브라우저 상관없이 저 함수가 코드적으로 하는 일에 집중해봅시다!

calculateNorm은 어떤 벡터를 정규화를 하는 작업을 합니다. 단위벡터를 얻는 과정이라고 생각하시면 될 거 같아요~!
따라서 작업하는 것도 x와 y값의 각각 제곱을 더해 루트를 씌워주는 거죠

calculateNorm은 2차원 벡터에 대한 연산만 합니다. 따라서 3차원 벡터가 매개변수로 대입되는건 사람의 눈으로 본다면 적절하지 않죠?? 그런데 타입스크립트는 정상으로 합니다. 구조적 타이핑적으로는 문제가 없는 내용이니까요~! 이해가 되셨을까요??

사람은 수학 문제를 푼다고 생각하는데 2차원 벡터를 정규화 해야하는데 3차원 벡터를 넣고 계산하지는 않죠??

따라서 이번 글에서는 이러한 구조적 타입이 가지는 한계를 어떻게 극복해 나갈 것인지 설명합니다. 뒤에 나오는 내용도 위의 말을 생각하며 읽으면 좋을 것 같습니다~!

추가로 동완님이 헷갈리시는게 당연한게 이펙티브 타입스크립트에 예시들은 꽤나 웹이랑은 동떨어진..? 로직들이 예시로 자주 나옵니다.

그래서 이해하기 더 어려운 부분도 있는 것 같아요~ 그러니 또 이해가 안간다면 질문해주세요~~

2023-09-16 17:12 UTC, 2yunseong commented on yunseong/attach_brand.md
> +```
함수의 매개변수는 Vector2D만 받는데, vec3D는 _brand 속성이 없으므로 에러가 발생한다고 생각하시면 됩니다~

2023-09-16 17:15 UTC, 2yunseong commented on yunseong/attach_brand.md
> +예시로 절대경로를 체크하는 코드를 살펴보겠습니다. 런타임에는 절대경로로 시작하는지 체크하기 쉽지만, 타입 시스템에서는 절대 경로를 판단하기 어렵기 때문에 상표 기법을 사용합니다.
@DWAN-00 
타입 시스템과 관련없이 foo 함수가 하는 일이 어떤 매개변수 path에 대해서 해당 path 변수가 절대 경로 형식인지 판단하는 함수를 예시로 든것이지, 타입시스템과는 관계가 없습니다.

2023-09-16 17:17 UTC, 2yunseong commented on yunseong/attach_brand.md
> +}
@DWAN-00 
어떤 인자 xs가 isSorted를 통해 정렬이 되었음을 (true)을 반환하면,  타입스크립트는 SortedList로 합니다. 위에 RouterPath예시를 읽고 다시한번 읽어보시기 바랍니다!

2023-09-16 17:18 UTC, 2yunseong commented
@loopy-lim 
> 배울 수록 javascript를 넘는 무언가가 완성이 되는거 같네요. 그래서 사람들이 typescript를 배척하는건가...?
가지기 힘든 건 시기하기 마련이죠 ㅋㅋ 우린 시기하지 맙시다

2023-09-16 17:23 UTC, 2yunseong commented
@bada308 
> 구조적 타이핑의 특성 때문에 코드가 의도치 않은 결과를 도출할 때가 있는데, 이를 방지하고자 상표 속성이라는 것을 사용한다.

맞습니다~ 👍 상표는 구조적 타이핑과 타입 체크가 가진 한계를 뛰어넘는 한 가지 방식 이라고 생각하면 될 것 같습니다~

> _brand 속성이 있는 값만 타입 검사를 통과하는데, is keyword 등을 사용해서 _brand 속성이 없는 값이라도 특정 조건을 만족한다면 타입 검사를 통과하도록 시스템을 속인다! 이런 과정을 통해 타입 가드를 할 수 있다.

네~ 실제 런타임에 존재할 수 없는 타입을 생성해 특정 타입 취급을 해버린다고 생각하면 될 것 같아요. 느낌이 오시겠지만 꼭 변수명을 `_brand`로 할 필요는 없고, 구분할 수 있는 무언가를 붙이면 될 것 같습니다~!

개인적으로는 '절대경로의 시작은 /로 시작해야한다.' '이진 탐색 함수에 인자로 넘어오는 배열은 반드시 정렬되어 있어야 한다' 같은 도메인적으로 안전성을 보장해야하는 코드들을 타입시스템에서 한다는게 상표 붙이기의 가장 유의미한 사용이 아닐까 생각이 드네요!

2023-09-16 17:24 UTC, 2yunseong commented on yunseong/attach_brand.md
> +따라서 AbsolutePath는 온전히 타입 시스템의 영역이 됩니다.
자바스크립트가 줄 수 없는 더 많은 정보를 준다고 생각합니다~

2023-09-16 17:37 UTC, DWAN-00 approved these changes

2023-09-19 11:16 UTC, merged