[09/10] 타입 단언보다는 타입 선언 사용하기
JNU-econovation/hotsix-study pull request #26
Opened 2023-09-10 02:36 UTC by bada308

2023-09-12 11:42 UTC, 2yunseong requested changes
남긴 질문만 하나 확인해주세요~!

2023-09-12 11:42 UTC, 2yunseong commented on bada/type_assertion_type_annotation.md
> +```
1. 제네릭을 통해 호출 시그너처를 선언한 부분에 대한 설명을 추가해주셨으면 좋겠습니다!
2. 아래의 예시로 들어주신 이 코드도 결국 null을 유니온하는 타입으로 추론될 수 밖에 없습니다.
```ts
const button = document.querySelector<HTMLButtonElement>("#myButton");
```
앞서 설명해주신 내용으로는 단언(assertion)을 통해 해결하였는데, 이 예시에서 말하고자 하는 바가 무엇인지 궁금합니다!

2023-09-13 05:51 UTC, loopy-lim approved these changes
애매하게 단언과 선언 이라는 단어를 다시 한번 알아야 할 것 같은 시간이었던 같습니다.

2023-09-13 05:51 UTC, loopy-lim commented on bada/type_assertion_type_annotation.md
> +- 하지만, 타입을 확신할 수 있는 경우에는 타입 단언을 이용해도 된다.
사실 저는 타입을 확신하는 일이 많이 없습니다.
단지 빈 Object를 만들고 이를 typescript가 착각하게 만드는 용도로 많이 사용합니다.
(위의 생각은 사실 좋은 생각이 아니기) 때문에 null을 더욱 많이 쓰는거 같습니다.

타입을 확신할 수 있는 경우가 무엇이 있을까요?

2023-09-16 04:56 UTC, dle234 approved these changes

2023-09-16 04:56 UTC, dle234 commented on bada/type_assertion_type_annotation.md
> +타입 단언도 가능하지만 함수의 리턴 타입을 통제할 때 함수 시그니처와 제네릭을 사용하면 더 안전하고 깔끔한 코드를 작성할 수 있을 것이다!!
querySelector 함수에서는 타입 단언도 사용할 수 있지만 제네릭을 사용하는 게 더 좋은 방법이라는 것을 알게 되었네요!

2023-09-19 11:17 UTC, 2yunseong approved these changes

2023-09-19 11:17 UTC, merged