[09/10] 래퍼객체 지양하기
JNU-econovation/hotsix-study pull request #27
Opened 2023-09-10 02:48 UTC by DWAN-00

[09/10] 래퍼객체를 지양해야하는 이유에 대해서 공부해봤습니다.

2023-09-12 11:58 UTC, 2yunseong requested changes
고생하셨습니다 👍 
(Assignee, Reviewer 설정 해주세요.)

2023-09-12 11:58 UTC, 2yunseong commented on dongwan/wrapper_object.md
> +//lib.dom.d.ts(18091, 5): The declaration was marked as deprecated here.
name을 쓰고 있다니.. 신기하네요

2023-09-12 11:58 UTC, 2yunseong commented on dongwan/wrapper_object.md
> +
이미지가 보이지 않아요. 수정바랍니다~~

2023-09-12 13:26 UTC, DWAN-00 commented on dongwan/wrapper_object.md
> +//lib.dom.d.ts(18091, 5): The declaration was marked as deprecated here.
JS에서는 동작이 가능하네요

2023-09-13 06:00 UTC, loopy-lim approved these changes
어려운 개념을 공부하셨군요!!
저도 아직도 prototype이 무엇인지 모르겠어요 ㅠㅠ

2023-09-13 06:00 UTC, loopy-lim commented on dongwan/wrapper_object.md
> +name[0] = "a";
여기서 에러가... 뜨죠? 아마 typescript는 string이 변경 불가능한 것인걸로 알아서 실행이 안되는 걸로 알아요!!

2023-09-16 05:12 UTC, dle234 approved these changes

2023-09-16 05:12 UTC, dle234 commented on dongwan/wrapper_object.md
> +원시타입은 객체에 할당할 수 있지만, 객체 타입을 원시타입에 할당할 수는 없다.
래퍼객체 : 원시타입을 객체화 시켜주는 객체형 데이터 타입
-> 변수의 프로퍼티에 접근할 때 래퍼 객체가 임시로 생성 (ex) a.length , a 는 string)
설명이 자세해서 래퍼타입이 뭔지, 왜 지양해야하는지 알게 됐네요!

2023-09-16 17:10 UTC, bada308 approved these changes

2023-09-16 17:26 UTC, 2yunseong approved these changes

2023-09-19 11:17 UTC, merged