styled-component 에 타입 지정하기
JNU-econovation/hotsix-study pull request #28
Opened 2023-09-10 03:34 UTC by dle234

styled-components 테마에 타입을 지정하는 방법에 대해 공부했습니다.(늦은 제출 죄송합니다ㅜㅜ)

2023-09-12 13:04 UTC, 2yunseong requested changes
고생하셨습니다~
(Assignee, Reviewer 설정 해주세요.)

2023-09-13 02:27 UTC, DWAN-00 approved these changes

2023-09-13 02:27 UTC, DWAN-00 commented on kayeon/타입스크립트와_stypedcomponent.md
> +import { defaultTheme } from "styled-components";
저도 이게 궁금합니다!

2023-09-13 02:27 UTC, DWAN-00 commented on kayeon/타입스크립트와_stypedcomponent.md
> +```
style에도 stirng으로 타입을 주고 ThemeProvider로 감싸주면서 타입이 있는 스타일을 작성할 수 있네요...! 좋은 글 감사합니다!

2023-09-13 06:04 UTC, loopy-lim approved these changes
아직도 styled-componts를 제대로 사용하지 못했지만, 이걸 보니 아직도 toss나 다른 큰 기업들인 tailwind를 쓰지 않는 것에 대한 이유를 알것 같아요!!

2023-09-13 06:04 UTC, loopy-lim commented on kayeon/타입스크립트와_stypedcomponent.md
> +```
declare을 여기서 이런식으로 확장할 수 있군요!

2023-09-13 06:04 UTC, loopy-lim commented on kayeon/타입스크립트와_stypedcomponent.md
> +```
recoil나, context API랑 비슷한 느낌이네요! css도 하나의 스토어를 통해 다룰 수 있고, 이를 타입으로서 관리한다는 것이 신기하네요!

2023-09-16 16:56 UTC, bada308 approved these changes

2023-09-16 16:56 UTC, bada308 commented on kayeon/타입스크립트와_stypedcomponent.md
> +```
공통 스타일의 타입을 관리하기 위해 declare 키워드를 사용할 수 있군요. 강의에서만 봤던 declare의 실제 사용법을 볼 수 있어서 좋았습니다!

2023-09-16 16:57 UTC, bada308 commented
styled-component에도 typescript를 사용할 수 있다는 것을 처음 알게 되어 좋았습니다!!

2023-09-17 02:52 UTC, 2yunseong commented
@dle234
이 커밋에 이번 주 관련 커밋이 들어가 있어요~! 삭제 부탁드립니다 !

2023-09-17 11:28 UTC, dle234 commented on kayeon/타입스크립트와_stypedcomponent.md
> +import { defaultTheme } from "styled-components";
앗 위에서 선언해준 타입입니다! styled.d.ts를 수정하여 styled-components 에서 바로 import 해 올 수 있습니다!

2023-09-19 11:18 UTC, 2yunseong commented
스터디 하차로 인한 Closed

2023-09-19 11:18 UTC, closed without merging