[09/10] satifies, hasOwnProperty
JNU-econovation/hotsix-study pull request #29
Opened 2023-09-10 13:01 UTC by loopy-lim

2023-09-12 14:10 UTC, 2yunseong requested changes
고생하셨습니다~ 추가 설명 요구드린 부분이 몇가지 있어요. 그 부분만 부탁드리겠습니다!

2023-09-12 14:10 UTC, 2yunseong commented on cheasueng/Typegar.md
> +그러면 언제 쓸까? 이제 함수형에서 잘 쓸 수 있다고 생각이 된다.
추가로 설명해주실 수 있나요? 이해가 잘 가지 않네욥

2023-09-12 14:10 UTC, 2yunseong commented on cheasueng/Typegar.md
> +}
👍 
프로토타입 체인을 통해 접근하는 방법이 왜 나쁜지도 설명해주시면 좋을 것 같아요!!

2023-09-13 06:04 UTC, loopy-lim commented on cheasueng/Typegar.md
> +typescript는 type gard방법이 여러가지입니다.
일요일에 고쳐서 push 날릴게요 ㅠㅠ 감사합니다

2023-09-13 06:05 UTC, loopy-lim commented on cheasueng/Typegar.md
> +}
하하.... 감사합니다 ㅋㅋㅋㅋ 오타가 잦네요...ㅠㅠㅠ 개발자로서 그러면 안되는데

2023-09-13 06:08 UTC, loopy-lim commented on cheasueng/Typegar.md
> +}
프로토타입 체인은 자신이 그 프로퍼티를 가지고 있지 않는다면 그 위의 프로퍼티에서 접근을 하게 됩니다.

하지만 hasOwnProperty를 사용하게 된다면 그 객체 자신만의 property를 검사하기 때문에 이를 사전에 차단을 하면 자신이 원하는대로 동작하지 않는 오류가 날 가능성이 현저히 작아진다는 것을 확인 할 수 있습니다.

2023-09-13 06:29 UTC, loopy-lim commented on cheasueng/Typegar.md
> +그러면 언제 쓸까? 이제 함수형에서 잘 쓸 수 있다고 생각이 된다.
이렇게 보니깐 밑의 예시가 부적절해보이네요!!

함수형을 쓸때는 매개변수가 매우 중요하다고 생각합니다. 예를 들면 union타입을 이용하여 분기점이 처리가 된다고 가정을 하죠

```ts
type AB = 'a' | 'b';
type Other = { name: string, content: string };
type Test = {
  ab: AB,
  other: AB | Other
}

const testByAs = {
  other: {name: 'asdf', content:'content'}
} as Test

const testBySatisfies = {
  ab: 'a',
  other: 'b',
} satisfies Test

const outputAB = (data: Test) => data.ab

console.log(outputAB(testByAs))
console.log(outputAB(testBySatisfies))
```

이런식으로 as로 단언을 하게 되면 ab가 없더라도 있는 것처럼 행동을 할 수 있습니다. 즉, 순수하게 함수를 쓰기 위해서 데이터가 있다고 보장하는 객체를 보장할 수 있는 기능이 추가되어 함수형에서 더 잘 쓸 수 있다라고 생각했습니다

2023-09-16 16:15 UTC, DWAN-00 requested changes

2023-09-16 16:42 UTC, dle234 approved these changes

2023-09-16 16:42 UTC, dle234 commented on cheasueng/Typegar.md
> +if (me.hasOwnProperty("toString")) {
hasOwnProperty를 이용하면 확실히 오류를 사전에 차단할 수 있을 것 같네요! 
'자신이 그 프로퍼티를 가지고 있지 않는다면 그 위의 프로퍼티에서 접근을 하는것'을 막는것은 확실히 오류를 막을 수 있을 것 같지만 직접 그 에러를 마주해본 적이 없어서 그런데 이런 상황에 대한 예시가 있을까요?

2023-09-16 17:23 UTC, bada308 approved these changes

2023-09-16 17:23 UTC, bada308 commented on cheasueng/Typegar.md
> +// error
제 생각엔 variable1에서 에러가 나는 게 아니라 variable2에서 발생하는 것 같습니다! @DWAN-00

2023-09-16 17:32 UTC, DWAN-00 approved these changes

2023-09-16 17:32 UTC, DWAN-00 commented on cheasueng/Typegar.md
> +// error
그렇게 생각하신 이유가 있을까요??
`Object literal may only specify known properties, and 'score' does not exist in type '{ grade: string; }'.`
할당해보니 오류가 뜨긴하는데

2023-09-17 01:32 UTC, bada308 commented on cheasueng/Typegar.md
> +// error
5개의 예시 중 error로 표기하신 부분 모두 type으로 선언한 속성이 실제 값에 없을 때인 것 같아서 댓글을 달았는데, 실제로 코드를 작성해보니까 5개 모두 에러가 뜨네요...?!

한 번 @loopy-lim 님의 설명을 들어봐야 할 것 같아요~

2023-09-17 02:07 UTC, loopy-lim commented on cheasueng/Typegar.md
> +// error
맞아요 다 error가 맞아요! 사실 긁어온거였는데, 여기 블로그 설명 자체가 틀....

2023-09-17 02:13 UTC, loopy-lim commented on cheasueng/Typegar.md
> +if (me.hasOwnProperty("toString")) {
```ts
class Human {
  name: string;
  age: number;
  constructor (name: string, age: number) {
    this.name = name;
    this.age = age;
  }
}

class HumanWithToString extends Human {
    toString() {
    return `name: ${this.name}, age: ${this.age}`;
    }
}

const cheasueng = new Human('채승', 25);
console.log(`${cheasueng}`)

const cheasuengWithToString = new HumanWithToString('채승', 25);
console.log(`${cheasuengWithToString}`)
```

이 두개가 어떻게 작동하는지, 어떤 결과값이 나오는지 확인하면 될꺼에요!

2023-09-19 11:18 UTC, 2yunseong approved these changes

2023-09-19 11:18 UTC, merged