[05/04] 타입스크립트 변수와 any unknown
JNU-econovation/hotsix-study pull request #3
Opened 2023-05-28 11:59 UTC by Klomachenko

2023-05-29 05:05 UTC, 2yunseong requested changes
잘 읽었습니다~ 공부를 재미있게 하는 규민님이 보여서 좋았습니다 ㅋㅋ

2023-05-29 05:05 UTC, 2yunseong commented on kyumin/타입정하기 애매할 때 (union type, any, unknown).md
> +    - 이새낀 뭐 그냥 바이러스임
비속어는 조금 걸러주세요~ 수정바랍니다.

2023-05-29 05:05 UTC, 2yunseong requested changes
잘 읽었습니다~ 공부를 재미있게 하는 규민님이 보여서 좋았습니다 ㅋㅋ

2023-06-03 04:22 UTC, loopy-lim approved these changes
사실 as any랑 as unknown이랑 차이점을 모르고 사용했었는데 다시 한번 보니깐 좋네요!!
공부의 흐름부터 어떻게 공부할지까지 재미있는 아티클을 읽은것 같습니다!!

2023-06-03 04:22 UTC, loopy-lim commented on kyumin/타입스크립트 기본 타입 정리.md
> +let 회원들 :string[] = ['kim', 'park']
[string]과 string[]의 차이점은 무엇인가요?
저는 잘... 모르겠더라구요 ㅠㅠ

2023-06-03 04:22 UTC, loopy-lim commented on kyumin/타입스크립트 쓰는 이유.md
> +타입에 관대한 자스의 모습이다…
이슈에서 이미지 등록하면 편해요!!

2023-06-03 04:22 UTC, loopy-lim commented on kyumin/타입스크립트 쓰는 이유.md
> +(멋있는 말로 자바스크립트는 Dynamic typing 을 지원하는 언어입니다)
사실 저는 ducktype이 정말 좋아보여서 javascript를 시작했답니다!!

2023-06-03 04:22 UTC, loopy-lim commented on kyumin/타입정하기 애매할 때 (union type, any, unknown).md
> +any 타입은 좋다고 막쓰면 안되는데
가끔 as unknown as any를 하긴 한답니다 ㅠㅠ  반성하겠습니다 ㅠㅠ

2023-06-03 04:22 UTC, loopy-lim approved these changes
사실 as any랑 as unknown이랑 차이점을 모르고 사용했었는데 다시 한번 보니깐 좋네요!!
공부의 흐름부터 어떻게 공부할지까지 재미있는 아티클을 읽은것 같습니다!!

2023-06-03 04:22 UTC, loopy-lim approved these changes
사실 as any랑 as unknown이랑 차이점을 모르고 사용했었는데 다시 한번 보니깐 좋네요!!
공부의 흐름부터 어떻게 공부할지까지 재미있는 아티클을 읽은것 같습니다!!

2023-06-03 12:38 UTC, merged