[09/17] 함수 오버로딩과 useRef오류 대처
JNU-econovation/hotsix-study pull request #31
Opened 2023-09-16 15:27 UTC by DWAN-00

[09/17] 함수 오버로딩에, useRef가 d.ts에 어떤식으로 오버로딩 되어 있는지에 대한 내용입니다.

2023-09-19 11:21 UTC, 2yunseong requested changes
동완님 덕분에 스터디에서 재밌는 주제로 이야기 나눴습니다~!! 스터디 때 나눈 이야기 몇개만 반영해주세요 :)

2023-09-19 11:21 UTC, 2yunseong commented on dongwan/function_overloading.md
> +function padding(top: number, right: number, bottom: number, left: number);
잘못된 선언 변경해주세요~

2023-09-19 11:21 UTC, 2yunseong commented on dongwan/function_overloading.md
> +function useRef<T = undefined>(): MutableRefObject<T | undefined>; // (3)
스터디 때 나눴던 오버로드 순서도 언급해주면 좋을 것 같습니다~!

2023-10-01 02:13 UTC, loopy-lim approved these changes
타입스크립트는 파면 팔수록 어렵네요 ㅠㅠㅠㅠ
순서도 보장해야한다니... 하지만 당연한거 같기도 하고
약간 신선한 충격이었어요!

2023-10-01 02:13 UTC, loopy-lim commented on dongwan/function_overloading.md
> +타입스크립트에서 동일한 이름에, **매개 변수만 다른** 여러 버전의 함수를 만드는 것
다른 언어와 차이를 보는 것도 좋을꺼 같아요!!

2023-10-04 05:34 UTC, merged