[10/1] 왜 타입스크립트는 Object.keys의 타입을 적절하게 추론하지 못할까
JNU-econovation/hotsix-study pull request #38
Opened 2023-10-01 02:52 UTC by bada308

2023-10-04 05:27 UTC, 2yunseong requested changes
제목을 보고 평소에 생각해보지 못했던 주제라 더 재밌게 읽었습니다~!

더군다나 타입스크립트가 얼마나 잘 짜여져 있는지 만든사람들이 대단하다는 생각도 드네요!

오고생하셨습니다~

2023-10-04 05:27 UTC, 2yunseong commented on bada/왜_타입스크립트는_Objectkeys의_타입을_적절하게_추론하지_못할까.md
> +
어차피 매개변수로 받는 타입이 Options라면,
이건 어떤지요?
```suggestion
const keys = Object.keys(options) as (keyof Options)[];

```

2023-10-04 05:27 UTC, 2yunseong commented on bada/왜_타입스크립트는_Objectkeys의_타입을_적절하게_추론하지_못할까.md
> +> `T` 타입의 객체가 있을 때, 해당 객체에 대해 하는 것은 `T`의 프로퍼티를 적어도 하나 포함하고 있다는 것뿐이다.
하는 것? 아는 것? 아는 것이겠죠?

2023-10-04 05:27 UTC, 2yunseong commented on bada/왜_타입스크립트는_Objectkeys의_타입을_적절하게_추론하지_못할까.md
> +  }
헉 Logical assignment 배워갑니다 새롭네요 ㅎㅎ

2023-10-04 05:27 UTC, 2yunseong commented on bada/왜_타입스크립트는_Objectkeys의_타입을_적절하게_추론하지_못할까.md
> +런타임에 `email` 프로퍼티로 인해 `validate`가 `undefined`가 될 것이고 호출될 때 오류를 발생하게 된다.
👍 👍 👍

2023-10-08 00:41 UTC, loopy-lim approved these changes
먼가 되게 신기하겐 문법을 본것 같기도 하고, ts와 object의 관계를 다시한번 더 생각해보게 되었습니다

2023-10-08 00:41 UTC, loopy-lim commented on bada/왜_타입스크립트는_Objectkeys의_타입을_적절하게_추론하지_못할까.md
> +  }
오... 저도 신기하네요 `||=`저도 저런 문법이 있었으면 좋겠는데... 했었는데 javascript에도 있었네요!!
다른 assingment도 다시 공부해볼게요,

2023-11-07 01:01 UTC, merged